- LevelAutomation:
    WEAA_10:
      characters: 傭兵 "炎之魔女",光輝衛土"魔禁",倒吊人"執劍者"
      isAuto: true
      isFreeAuto: false
      autoDeploy: true
      defaultDifficulty: true
      highRewardFirst: true
    TRTA_09:
      characters: ''
      isAuto: true
      isFreeAuto: false
      autoDeploy: true
      defaultDifficulty: true
      highRewardFirst: true
- Material_Mission:
    mission: WEAA_10,TRTA_09
